### ISSUE TITLE
size of input tensor and input format are different

### ISSUE THREAD

**Issue by luxinfeng** [soochan-lee/MR-GAN#1]
Hello ,when i run the main.py to train the cityscapes , it occurs "AssertionError: size of input tensor and input format are different.         tensor shape: (1, 3, 512, 512), input_format: CHW
"

**Comment by soochan-lee** [comment]
Hi!
Could you give some more information about the error?
I've checked the following command but everything seems to work well.
```bash
$ python main.py --mode mr --config ./configs/pix2pix-cityscapes_256x256-gaussian-mr1.yaml --log-dir logs/mr
```
